controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

homepage:
  path: /homepage
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
  defaults:
    route: 'app_index'
    keepQueryParams: true
    permanent: true

accueil:
  path: /accueil
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
  defaults:
    route: 'app_index'